### ISSUE TITLE
multiple processes Error in main_py.py

### ISSUE THREAD

**Issue by lsjw** [csiesheep/hin2vec#17]
When i use main_py.py to run the example and add the option --num_processes = 2 ,there is an Error as follows:

Load a HIN...
U 34
{'U-U': 0}
0 16
1 3
2 1
3 2
4 5
5 2
6 3
7 2
8 9
9 6
10 10
11 6
12 3
13 4
14 4
15 4
16 5
17 4
18 2
19 4
20 3
21 12
22 2
23 17
24 2
25 2
26 2
27 2
28 2
29 5
30 3
31 4
32 3
33 2
Generate random walks...
c:\users\user\appdata\local\temp\tmpfhxsje
Reading nodes 30000
Reading paths 90000
0 0(count:33660, inverse:False)
1 0,0(count:33320, inverse:False)
2 0,0,0(count:32980, inverse:False)
training bytes: 158853
distinct node count: 34
distinct path count: 3
start training
Traceback (most recent call last):
  File "C:/develop/pythonWorkspace/hin2vec/main_py.py", line 164, in <module>
    sys.exit(main(graph_fname, node_vec_fname, path_vec_fname, options))
  File "C:/develop/pythonWorkspace/hin2vec/main_py.py", line 60, in main
    k_hop_neighbors=neighbors,
  File "C:\develop\pythonWorkspace\hin2vec\model\mp2vec_s.py", line 161, in train
    p.start()
  File "C:\develop\python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\develop\python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\develop\python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\develop\python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\develop\python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\develop\python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\develop\python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\develop\python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\develop\python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\develop\python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\develop\python27\lib\pickle.py", line 568, in save_tuple
    save(element)
  File "C:\develop\python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\develop\python27\lib\multiprocessing\forking.py", line 67, in dispatcher
    self.save_reduce(obj=obj, *rv)
  File "C:\develop\python27\lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\develop\python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\develop\python27\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "C:\develop\python27\lib\pickle.py", line 300, in save
    self.save_global(obj)
  File "C:\develop\python27\lib\pickle.py", line 754, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <class 'c_double_Array_100'>: it's not found as __main__.c_double_Array_100

Please help me how to deal with it .Thx for your time !

**Comment by csiesheep** [comment]
Hi, Thanks for asking. But I can not reproduce this issue on my environment (Ubuntu 18.04). What environment you use?
