### ISSUE TITLE
Key Error when test with a toy network

### ISSUE THREAD

**Issue by fanyike** [csiesheep/hin2vec#8]

**Comment by fanyike** [comment]
The toy network used here is 
#source_node	source_class	dest_node	dest_class	edge_class
1	U	2	U	U-U
when I run the code, I got the following error:
Load a HIN...
U 2
{'U-U': 0}
1 1
Generate random walks...
Traceback (most recent call last):
  File "/root/userfolder/projects/HIN2Vec/main.py", line 146, in <module>
    sys.exit(main(args[0], args[1], args[2], options))
  File "/root/userfolder/projects/HIN2Vec/main.py", line 32, in main
    for walk in g.random_walks(options.walk_num, options.walk_length):
  File "/root/userfolder/projects/HIN2Vec/ds/network.py", line 303, in random_walks
    walk = self.a_random_walk(node, length)
  File "/root/userfolder/projects/HIN2Vec/ds/network.py", line 257, in a_random_walk
    if len(self.graph[node]) == 0:
KeyError: 1

**Comment by Tabris223** [comment]
I already fix this problem.. next_node may be not in graph.
